services:
  - type: web
    name: writory-poetry-contest
    env: node
    region: oregon
    plan: pro # Upgraded to pro plan for 5-10k users
    buildCommand: cd server && npm run render-build
    startCommand: cd server && npm run render-start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    # Performance optimizations for 5-10k concurrent users
    scaling:
      minInstances: 2
      maxInstances: 10 # Auto-scale up to 10 instances for high load
    # Resource allocation for 5-10k users
    resources:
      cpu: 2 # 2 CPU cores (pro plan)
      memory: 4GB # 4GB RAM (pro plan)
    # Advanced performance settings
    performance:
      enableCaching: true
      enableCompression: true
      enableGzip: true